#!/bin/bash
# ---------------------------------------------------------------------------
#  Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

if [ "$(uname)" == "Darwin" ]
then
    CURRENT_PATH=$(dirname "$0")
else
    CURRENT_PATH="$(dirname "$(readlink -f "$0")")"
fi

\cp $CURRENT_PATH/ballerina-command-@version@/lib/ballerina-command-@version@.jar $CURRENT_PATH/../lib

if [ $? -ne '0' ]; then
  echo "error occurred while copying ballerina jar"
  # remove if copied with an error.
  if [ -f "$CURRENT_PATH/../lib/ballerina-command-@version@.jar" ]; then
        rm -rf $CURRENT_PATH/../lib/ballerina-command-@version@.jar
  fi
  exit $?
fi

rm -rf $CURRENT_PATH/../bin/bal
\cp $CURRENT_PATH/ballerina-command-@version@/bin/bal $CURRENT_PATH/../bin
chmod 755 $CURRENT_PATH/../bin/bal

if [ $? -ne '0' ]; then
  echo "error occurred while copying ballerina file."
  # remove already copied jar.
  if [ -f "$CURRENT_PATH/../lib/ballerina-command-@version@.jar" ]; then
        rm -rf $CURRENT_PATH/../lib/ballerina-command-@version@.jar
  fi
  exit $?
fi

if [ -f "$CURRENT_PATH/ballerina-command-@version@/scripts/bal_completion.bash" ]
then
\cp $CURRENT_PATH/ballerina-command-@version@/scripts/bal_completion.bash $CURRENT_PATH/../scripts
fi

if [ -f "$CURRENT_PATH/ballerina-command-@version@/scripts/_bal" ]
then
\cp $CURRENT_PATH/ballerina-command-@version@/scripts/_bal $CURRENT_PATH/../scripts
fi

if [ -d "$CURRENT_PATH/../dependencies/jdk-21.0.5+11-jre" ]
then
chmod -R 755 $CURRENT_PATH/../dependencies/jdk-21.0.5+11-jre
fi

if [ $? -ne '0' ]; then
  echo "error occurred while copying completion script files."
fi

if [ -f "~/.ballerina/completion/_bal" ]
then
  \cp $CURRENT_PATH/ballerina-command-@version@/scripts/_bal ~/.zsh/completion
fi

if [ $? -ne '0' ]; then
  echo "error occurred while updating zsh completion script."
fi

echo "Updating environment variables"
if [ -f "/usr/lib/ballerina/bin/ballerina" ] 
then
    ln -sf /usr/lib/ballerina/bin/bal /usr/bin/bal
    echo "export BALLERINA_HOME=/usr/lib/bal" >> /etc/profile.d/wso2.sh
    rm -f /usr/lib/ballerina/bin/ballerina
    chmod 755 /usr/lib/ballerina/bin/bal
elif [ -f "usr/lib64/ballerina/bin/ballerina" ] 
then
    ln -sf usr/lib64/ballerina/bin/bal /usr/bin/bal
    rm -f usr/lib64/ballerina/bin/ballerina
    chmod 755 usr/lib64/ballerina/bin/bal
elif [ -f "/Library/Ballerina/bin/ballerina" ]
then
    rm -f /Library/Ballerina/bin/ballerina
    echo "/Library/Ballerina/bin" >> /etc/paths.d/bal
    chmod 755 /Library/Ballerina/bin/bal
fi

echo "Update tool version updated to the latest version: @version@"
echo "Cleaning old files..."

for file in $CURRENT_PATH/../lib/*; do
    if [ -f "$file" ] && [[ "$file" == *ballerina-command*.jar ]] && [[ "$file" != *ballerina-command-@version@.jar ]]; then
	rm -rf $file
    fi
done
