name: Build master branch

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PAT }}
      run: |
        ./gradlew build jacocoTestReport --scan
    - name: Generate Codecov Report
      uses: codecov/codecov-action@v1
